# Site settings
title: Туалетные прицепы
email: toilet@trailer.com
description: > # this means to ignore newlines until "baseurl:"
    Скоро важное мероприятие на открытом воздухе? Необходимо создать комфортные условия для времяпрепровождения? Аренда туалетного прицепа - отличное решение, которое обеспечит #комфорт и удобство для ваших гостей!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Build settings
markdown: kramdown
